import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    domains: [
      "www.ozbargain.com.au",
      "images.unsplash.com",
      "img.youtube.com",
      "assets.coindesk.com",
      "cryptonews.com",
      "bitcoin.org",
      "blockchain.com",
      "coinbase.com",
      "cointelegraph.com",
      "decrypt.co",
      "news.bitcoin.com",
      "bitcoinmagazine.com",
      "cryptoslate.com",
      "newsbtc.com",
      "cryptopotato.com",
      "beincrypto.com",
      "cryptodaily.co.uk",
      "coingape.com",
      "u.today",
      "ambcrypto.com",
      "zycrypto.com",
      "bitcoinist.com",
      "dailyhodl.com",
      "cryptobriefing.com",
      "cryptonewsz.com",
      "investing.com",
      "finance.yahoo.com",
      "cnbc.com",
      "reuters.com",
      "bloomberg.com",
      "wsj.com",
      "nytimes.com",
      "forbes.com",
      "businessinsider.com",
      "marketwatch.com",
      "ft.com",
      "theguardian.com",
      "bbc.co.uk",
      "abc.net.au",
      "news.com.au",
    ],
    remotePatterns: [
      {
        protocol: "https",
        hostname: "**",
      },
    ],
  },
};

export default nextConfig;
